### ISSUE TITLE
Draenei shaman - Step 19 -  Should have "grind to level 4" before "Talk to Firmanvaar"

### ISSUE THREAD

**Issue by caribez** [PolarCookie/PolarGuides#1]
The quest Call of Earth requires level 4. I was a few bars short (I'm guessing I had luck with getting quest objects) so I had to go out and grind a few mobs. Would be great if an extra step was added as a precaution, that you should grind to level 4 before going there. 

This might also be relevant for other classes playing as Draenei if they have a level 4 quest.

**Comment by PolarCookie** [comment]
Thank you for finding this one!
