### ISSUE TITLE
Guide says to pick up a level 61 quest at level 60.

### ISSUE THREAD

**Issue by ryangodlien** [PolarCookie/PolarGuides#12]
In Hellfire Peninsula the guide has you try to pick up the quest "Helping the Cenarion Post" from Amaan the Wise in Temple of Talhamat. This quest isn't available until level 61 and this is part of the guide when you are still level 60.

Step 118 - Hellfire Peninsula guide.

![wowscrnshot_011819_173735](https://user-images.githubusercontent.com/29844358/51418251-0828d600-1b48-11e9-82af-aea075e1a5cd.jpg)

**Comment by PolarCookie** [comment]
It's most likely that I never updated the ding steps for TBC, and TBC needing a lot more xp than Wrath.
https://wow.gamepedia.com/Experience_to_level for reference.

A Ramparts/BF run will hopefully fix it, but I'll look into changing the TBC route.

**Comment by PolarCookie** [comment]
I added Hellfire Ramparts, Blood Furnace and reordered the quests in Hellfire for the solo guide.
Duo guide remains mostly the same as that will continue in Azeroth until level ~62.
