### ISSUE TITLE
Quest [37] Liquid Stone

### ISSUE THREAD

**Issue by Ofecks** [PolarCookie/PolarGuides#13]
Not available until you complete the "study of elements" chain from the other gnome.  See here: https://github.com/Atlantiss/NetherwingBugtracker/issues/4294

Should be moved to a further step.

**Comment by PolarCookie** [comment]
I don't trust Netherwing's "research" about anything, and in typical fashion they don't provide evidence for their case, so I'm going with TrinityCore on this one.
I did take the opportunity to fix the steps a bit.
