### ISSUE TITLE
Quest [49] The Dunemaul Compound

### ISSUE THREAD

**Issue by Ofecks** [PolarCookie/PolarGuides#14]
Minor typo.  Guide text says to kill 5 each of Brutes/Enforcers, but it's 10 each in TBC apparently.

**Comment by PolarCookie** [comment]
It's meant that you kill 5 of each then finish them off at the later step, as there are not that many in the ruins.

**Comment by Ofecks** [comment]
Ok, I misunderstood then.

**Comment by PolarCookie** [comment]
I can try rewording the step, it wasn't obvious what I meant.

**Comment by PolarCookie** [comment]
I removed the line entirely, didn't need it.
