### ISSUE TITLE
Quest [60] The First And The Last

### ISSUE THREAD

**Issue by Ofecks** [PolarCookie/PolarGuides#16]
Line 8815 in solo guide.  Says to talk to King Varian Wrynn at 80,38.4 to pick up this quest in SW.  King Wrynn isn't there in TBC, and the coords are invalid.  Instead it should say to pick it up from Highlord Bolvar Fordragon at 78.2, 18.1.

Additionally, the next step (line 8819) says to turn it in at Mathias Shaw at 78.3,70.7.  That's the correct NPC but the coords are again invalid.  Shaw is at 75.8, 59.9 in TBC.

**Comment by PolarCookie** [comment]
questline removed for both solo guides
