### ISSUE TITLE
Quest [60] Past Endeavors

### ISSUE THREAD

**Issue by Ofecks** [PolarCookie/PolarGuides#18]
Line 9422 in the solo guide says to pick up this quest, but from what I can tell (checked both TBC and Wrath databases), it's horde-only.  There's no turn-in step in the guide, so the pickup should be removed.

**Comment by PolarCookie** [comment]
https://wow.gamepedia.com/Past_Endeavors
It's supposed to be available for alliance past patch 2.3, but servers vary a lot on this.
I can make a comment about it, since Netherwing won't have it anyway, but other servers should.

**Comment by PolarCookie** [comment]
Though to be fair, if Netherwing doesn't include this quest they have to remove Mudsprocket.
