### ISSUE TITLE
Quest [69] Rebuilding the Staff - possibly out of order

### ISSUE THREAD

**Issue by Ofecks** [PolarCookie/PolarGuides#25]
This quest has you killing the ghosts at the ruins of Enkaat, when you've already been there killing them for the Mark V escort and gems-on-the ground for [68] You're Hired!.  Is it possible to hold off on the Enkaat ruins quests until you get to this one?

**Comment by PolarCookie** [comment]
No, that part is a bit tricky.
[Rebuilding the Staff](https://db.rising-gods.de/?quest=10300) at Ruins of Enkaat needs [The Archmage's Staff](https://db.rising-gods.de/?quest=10173) at Arklon Ruins, but [Invaluable Asset Zapping](https://db.rising-gods.de/?quest=10203) at Arklon Ruins needs [You're Hired!](https://db.rising-gods.de/?quest=10186) at Ruins of Enkaat. So you have to backtrack to either of the two.
