### ISSUE TITLE
[32] Satyr Slaying! quest incorrect coordinates

### ISSUE THREAD

**Issue by Ofecks** [PolarCookie/PolarGuides#9]
Line 4624 in solo guide:  the correct mobs that drop the horns are flagged, but the area coordinates are wrong.  It's saying you should kill the ones down in Satyrnaar where the wood piles are looted, but they don't drop them.  You should be up above where you previously found Anilia.  Roughly 78.5, 45.5.  Maybe split this step up into two?

**Comment by PolarCookie** [comment]
The Satyrnaar Satyrs are supposed to drop horns, all 3 Satyr camps should work.
https://db.rising-gods.de/?quest=1032
WotLK database but it shows what I'm saying, and this is supposed to be the case for Vanilla/TBC as well.
I'm 99% certain I got a drop from the Satyrnaar Satyrs on Netherwing.
